[package]
name = "warpgate-orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
warpgate-common = { path = "../warpgate-common" }
axum = "0.8.9"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing = "0.1.44"
serde = { version = "1.0.229", features = ["derive"] }
